import { Block } from '../../../shared/types';
import { Timestamp } from 'firebase/firestore';

export const DEFAULT_BLOCKS: Omit<Block, 'id' | 'createdAt'>[] = [
  {
    name: 'Learning',
    icon: 'book.fill',
    color: '#3B7A57',
    duration: 7200,
    dailyGoal: 3600,
    order: 0,
  },
  {
    name: 'Portfolio',
    icon: 'briefcase.fill',
    color: '#1A6B8A',
    duration: 7200,
    dailyGoal: 3600,
    order: 1,
  },
  {
    name: 'Exercise',
    icon: 'figure.run',
    color: '#C0392B',
    duration: 3600,
    dailyGoal: 1800,
    order: 2,
  },
  {
    name: 'Deep Work',
    icon: 'brain.head.profile',
    color: '#8E44AD',
    duration: 9000,
    dailyGoal: 7200,
    order: 3,
  },
];

export const SF_SYMBOLS = [
  'book.fill',
  'briefcase.fill',
  'figure.run',
  'brain.head.profile',
  'pencil',
  'paintbrush.fill',
  'music.note',
  'camera.fill',
  'laptopcomputer',
  'desktopcomputer',
  'keyboard',
  'headphones',
  'mic.fill',
  'guitars.fill',
  'pianokeys',
  'heart.fill',
  'star.fill',
  'flame.fill',
  'bolt.fill',
  'chart.bar.fill',
  'doc.text.fill',
  'folder.fill',
  'archivebox.fill',
  'tray.fill',
  'envelope.fill',
  'phone.fill',
  'video.fill',
  'play.fill',
  'pause.fill',
  'stopwatch.fill',
  'clock.fill',
  'calendar',
  'map.fill',
  'location.fill',
  'house.fill',
  'building.2.fill',
  'cart.fill',
  'bag.fill',
  'creditcard.fill',
  'banknote.fill',
  'trophy.fill',
  'medal.fill',
  'rosette',
  'target',
  'person.fill',
  'person.2.fill',
  'person.3.fill',
];
